### ISSUE TITLE
Support project-specific dep overrides / settings in pyproject.toml

### ISSUE THREAD

**Issue by mdekstrand** [conda-incubator/conda-lock#115]
It would be useful for `conda-lock`'s `pyproject.toml` support if it could support configuring dependency-specific information directly in `pyproject.toml`. I see at least two things that would be useful to configure:

- A dependency needs to be installed by Pip; this will probably only work with `-k env`, but would add the dependency to a `pip` section.
- The Conda package name for a dependency (in case something isn't in the global rename file, or to remove dependency on it)

This could look something like:

```toml
[tool.cargo-lock.dependencies]
hpfrec = { source = "pip" }
msgpack = { conda-package = "python-msgpack" }
```
