### ISSUE TITLE
[Feature Request] Private pypi repository

### ISSUE THREAD

**Issue by horaceg** [conda-incubator/conda-lock#135]
First of all, `conda-lock` is amazing and very convenient for prod worflows, thank you for this.

It would be useful for my use-case to add the possibility of installing pip dependencies based on a private repository.

In `pyproject.toml` with poetry, this is something like

```toml
[[tool.poetry.source]]
name = "private"
url = "https://.../packages/pypi/simple"
secondary = true # or false
```

in `requirements.txt`, it looks like

```
--extra-index-url https://.../pypi/simple
my-private-package 
```
