### ISSUE TITLE
Error when running conda-lock for env.yml containing typing-extensions

### ISSUE THREAD

**Issue by KukumavMozolo** [conda-incubator/conda-lock#137]
Hello there,

I tried to generate a lock file for an env.yml containing hera-workflows 1.5.1.
I got the following error:
`/anaconda3/envs/test/lib/python3.8/site-packages/conda_lock/src_parser/__init__.py", line 249, in _apply_categories
    for dep in planned[item].dependencies
KeyError: 'typing_extensions'
`
I found that hera-workflows has typing-extensions==4.0.1 as a requirement. Here is a minimal example to recreate this error:
```

name: test
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pip
  - python==3.8.11
  - pip:
      - typing-extensions==4.0.1

```

execute with: `conda-lock -f test.yml -p osx-64 -p linux-64 
`

**Comment by mariusvniekerk** [comment]
Can you try using `typing_extensions` ?  There might be something somewhat incorrect going on with seperator normalization

**Comment by KukumavMozolo** [comment]
What do you mean by that? 

> Can you try using typing_extensions ?

**Comment by mariusvniekerk** [comment]
#139 Should solve some of those issues. Let me know if that works for you

**Comment by matbun** [comment]
Hi! I still have this problem here, when running:

```bash
conda-lock lock -f ai/pytorch-env.yml -k explicit
```

conda-lock version: 1.4.0

```yaml
# ai/pytorch-env.yml

name: ai-training
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9.12
  - pytorch::pytorch=1.13.1
  - pytorch::torchvision=0.14.1
  - pytorch::cpuonly
  - lightning=2.0.0
  - torchmetrics
  - mlflow>=2
  - typer
  - rich
  - pyyaml
  - omegaconf

  # Pip dependencies
  - pip
  - pip:
    - jsonargparse[signatures]>=4.17.0

platforms:
  - linux-64
  - osx-64
  - win-64
```

Error:

```text
KeyError: Package('typing-extensions', '4.6.1')
```

Help please!
