### ISSUE TITLE
Defining pip version as well as pip-dependencies

### ISSUE THREAD

**Issue by vicecea** [conda-incubator/conda-lock#190]
Hi,

Thanks for the great work on this project!
I'm trying to define both pip-dependencies as well as a pip version, but I can't get it to work and wonder if I'm missing something.

e.g., for pip-dependencies this works ↓
```
dependencies:
  - python=3.7.3
  - pip:
      pytest: 6.2.2
```

and defining a pip version works, e.g. ↓
```
dependencies:
  - python=3.7.3
  - pip=19.3.1
```

but I have failed to get both working together, e.g. this doesn't work for me ↓
```
dependencies:
  - python=3.7.3
  - pip=19.3.1
  - pip:
      pytest: 6.2.2
```

neither does this work ↓
```
dependencies:
  - python=3.7.3
  - pip=19.3.1:
      pytest: 6.2.2
```

I appreciate any pointers to a solution here.
Thanks!

**Comment by mariusvniekerk** [comment]
you might be able to force it using two files

```yaml
# base.environment.yaml
dependencies:
  - python 3.7,.3
  - pip 19.3.1
```

```yaml
# addon.environment.yaml
dependencies:
  - pip:
     - pytest =19.3.1
```

and then locking using 
```
conda-lock -f base.environment.yaml -f addon.environment.yaml
```
