### ISSUE TITLE
Trying to install private GitHub repo as pip package.

### ISSUE THREAD

**Issue by seanyboi** [conda-incubator/conda-lock#197]
Hi there,

I am trying to perform `conda lock -p osx-64 -p osx-arm64 -p linux-64 -p linux-aarch64 -f environment.yml --filename-template 'x-{platform}.lock'` with an evironment.yml file like so that contains a private pip package hosted in a private GitHub repo:

```python
name: xxxx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - scikit-learn=1.0.0
  - pip
  - boto3
  - slackclient
  - conda-lock
  - pip:
    - git+ssh://git@github.com/xxxxxxxxxx
    - pytz
```

But I get the error `pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'+ssh://g'": Expected string_end`. 

I can easily install the private repo by running the normal `conda env create --prefix ./env -f environment.yml`. So just wondering what I'm doing wrong here :)

**Comment by ovidner** [comment]
FWIW, I've found something of a workaround for now. An example from my own code:
```yaml
dependencies:
  - python
  - pip:
      - pymatbridge @ https://github.com/arokem/python-matlab-bridge/archive/51c0e79aa6ecb9ae11d02ad367c1bfa0b27c2caa.zip#sha256=
```

The `package @ url` form (https://pip.pypa.io/en/stable/reference/requirement-specifiers/) seems to be key. Note that it only seems to work with zips or tarballs, not git specifiers (does that even work with private repos?). The `md5` or `sha256` key must also be present but seems not to be checked. Not sure if the package's dependencies will be locked with this approach. 

A lot of disclaimers, as you see. :)
