### ISSUE TITLE
[Feature Request] Add "requested_spec" details to the lock file

### ISSUE THREAD

**Issue by AlbertDeFusco** [conda-incubator/conda-lock#198]
I've been thinking that conda-lock can be used as an expanded version of `conda env export`. What would be very interesting for me is to record the requested version in the lock file.

Here's an example

```yaml
# The environment.yml file
name: minimal

dependencies:
  - python>3.9

platforms:
  - linux-64

```

And and excerpt from the proposed conda-lock.yml with a new key `requested`. It is non-false for any package not listed in the environment.yml file.

```yaml
# The proposed change to conda-lock.yml
- category: main
  dependencies:
    libgcc-ng: '>=7.5.0'
    readline: '>=8.0,<9.0a0'
    zlib: '>=1.2.12,<1.3.0a0'
  hash:
    md5: 94e50b233f796aa4e0b7cf38611c0852
    sha256: 2778a98881e694c4cc602f14da045feb20d4c3680776935e252732f9ef223852
  manager: conda
  name: sqlite
  optional: false
  platform: linux-64
  url: https://repo.anaconda.com/pkgs/main/linux-64/sqlite-3.38.3-hc218d9a_0.conda
  version: 3.38.3
  requested: False
- category: main
  dependencies:
    bzip2: '>=1.0.8,<2.0a0'
    ld_impl_linux-64: ''
    libffi: '>=3.3,<3.4.0a0'
    libgcc-ng: '>=7.5.0'
    libuuid: '>=1.0.3,<2.0a0'
    ncurses: '>=6.3,<7.0a0'
    openssl: '>=1.1.1n,<1.1.2a'
    readline: '>=8.0,<9.0a0'
    sqlite: '>=3.38.0,<4.0a0'
    tk: '>=8.6.11,<8.7.0a0'
    tzdata: ''
    xz: '>=5.2.5,<6.0a0'
    zlib: '>=1.2.11,<1.3.0a0'
  hash:
    md5: f931504bb2eeaf18f20388fd0ad44be4
    sha256: 3ac2d9165dbc89e4b309a2fa192c01f7e65a2fd47fad588bad44c66c19ad9af8
  manager: conda
  name: python
  optional: false
  platform: linux-64
  url: https://repo.anaconda.com/pkgs/main/linux-64/python-3.10.4-h12debd9_0.tar.bz2
  version: 3.10.4
  requested: 'python>3.9'
```
