### ISSUE TITLE
`<TOKEN>` in all package URLs when using Mamba

### ISSUE THREAD

**Issue by leroyvn** [conda-incubator/conda-lock#211]
Hi, I'm updating my lock files and conda-lock using Mamba (I have a fairly big environment and Mamba speeds up the locking process). I get broken package URLs: all of them contain a `/t/<TOKEN>` string and has Conda fail silently when I try to use the created lock file to update or create an environment. Here is an example:
```
https://conda.anaconda.org/t/<TOKEN>/conda-forge/linux-64/ca-certificates-2022.6.15-ha878542_0.tar.bz2
```

### Minimal example

This is what I used as my `environment.yml` file:

```yaml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
```

Run the following command:

```
conda-lock --mamba --file environment.yml
```

### Configuration

- Platform: macOS 12.4
- Python version: Python 3.10.5 (from Miniforge)
- Conda version: 4.13.0
- Mamba version: 0.24.0

**Comment by mariusvniekerk** [comment]
When accessing a private channel using conda lock the environment variable form as described in https://conda-incubator.github.io/conda-lock/authenticated_channels/ is the recommended approach. 

What does your condarc look like?

Additionally versions for python, conda-lock, conda and mamba are quite likely needed to reproduce your issue.

**Comment by leroyvn** [comment]
Hi @mariusvniekerk, thanks for such a quick reply.

I only used public channels (including a custom one on anaconda.org, which is not part of the reproducer I posted); could authentication be an issue, still?

I also updated the main issue description with the information you requested, and even a bit more.

**Comment by lesteve** [comment]
I saw something similar at one point when I updated to mamba 0.23. The thing that fixed it for me was to move my anaconda-client tokens out of the way. This did it for me:
```
mv ~/.continuum/anaconda-client{,.bak}
```

**Comment by leroyvn** [comment]
> I saw something similar at one point when I updated to mamba 0.23. The thing that fixed it for me was to move my anaconda-client tokens out of the way. This did it for me:
> 
> ```
> mv ~/.continuum/anaconda-client{,.bak}
> ```

This works for me as well. Can this be considered as a fix? I can't remember when those tokens were defined and when I use them.

**Comment by lesteve** [comment]
> Can this be considered as a fix?

Well that's a work-around at least :smile:.

> I can't remember when those tokens were defined and when I use them.

I am guessing they are used by anaconda-client for example to upload conda packages to anaconda.org but I am not 100% sure.

**Comment by riccardoporreca** [comment]
This issue is definitely biting with the anaconda commercial editions, where we are given a token and instructions to add the following to .condarc

```
restore_free_channel: false
default_channels:
  - https://repo.anaconda.cloud/t/<THE_ACTUAL_TOKEN>/repo/main
  - https://repo.anaconda.cloud/t/<THE_ACTUAL_TOKEN>/repo/msys2
  - https://repo.anaconda.cloud/t/<THE_ACTUAL_TOKEN>/repo/r
channels:
  - defaults
 ````

I guess this is the case for @leroyvn at the top, somehow masked in the `conda config --show` output by the fact that conda would hide completely the token `/t/<TOKEN>` part.

I can confirm the issue for an even more minimal example

```tml
# environment.yml file
channels:
  - defaults
dependencies:
  - python=3.8
  - isort=5.9.3
```

After running `conda-lock --mamba -f environment.yml`

```yml
# example extract from conda-lock.yml
- category: main
  dependencies: {}
  hash:
    md5: 6d4c2a14b2bdebc9507442efbda8208e
    sha256: d7bff8f6f6662c1d35fb3b353635e574e1ee8b59dbef78626c398aac0872e9ca
  manager: conda
  name: ca-certificates
  optional: false
  platform: linux-64
  url: https://repo.anaconda.cloud/t/<TOKEN>/repo/main/linux-64/ca-certificates-2022.07.19-h06a4308_0.conda
  version: 2022.07.19
- category: main
  dependencies:
    python: '>=3.6.1,<4.0'
  hash:
    md5: 75f2497fe01a9ac6208d72e26066b76a
    sha256: c20bf1d70180ea452b16b89b9a62aab2192a8b8ad71d63c46beabc1fbb9b2451
  manager: conda
  name: isort
  optional: false
  platform: osx-64
  url: https://repo.anaconda.cloud/t/<TOKEN>/repo/main/noarch/isort-5.9.3-pyhd3eb1b0_0.conda
  version: 5.9.3
- category: main
  dependencies: {}
  hash:
    md5: cd032245d4b08e14cfd6ca27b647a699
    sha256: 61082ca98bdf0025bf80122991606b120e1e9636eb03af6c27712733014a1193
  manager: conda
  name: ca-certificates
  optional: false
  platform: win-64
  url: https://repo.anaconda.cloud/t/<THE_ACTUAL_TOKEN>/repo/main/win-64/ca-certificates-2022.07.19-haa95532_0.conda
  version: 2022.07.19
```
The funny thing here (which might help investigating), is that I see the actual token (shown as `<THE_ACTUAL_TOKEN>`) instead of the verbatim problematic `<TOKEN>` for the `win-64` as I am on such platform and the package was cached as part of an actual installation. Running `mamba clean -afy` and then again `conda-lock` results in `<THE_TOKEN>` also for `win-64`.

The example above is for the following versions
```
python                    3.10.4               hbb2ffb3_0
conda                     4.13.0          py310haa95532_0
mamba                     0.25.0          py310h9376f3e_1
conda-lock                1.1.1              pyhd8ed1ab_0
```

**Comment by riccardoporreca** [comment]
Meanwhile, the only workaround I have found is defining an environment variable `ANACONDA_TOKEN` and not relying on the `defaults` from the (global) `.condarc`:
```yml
# environment.yml file
channels:
  - https://repo.anaconda.cloud/${ANACONDA_TOKEN}/repo/main
  - https://repo.anaconda.cloud/${ANACONDA_TOKEN}/repo/msys2
  - https://repo.anaconda.cloud/${ANACONDA_TOKEN}/repo/r
dependencies:
  - python=3.8
  - isort=5.9.3
```
which is less ideal as one would normally manage default channels as part of the (global) conda configuration, especially for such enterprise-level commercial edition token
