### ISSUE TITLE
Document (revise?) how dependencies from file sources are combined

### ISSUE THREAD

**Issue by riccardoporreca** [conda-incubator/conda-lock#222]
When processing file sources, it looks like only the last specification of a conda package version (by package name) is preserved

e.g.
```yml
# environment-foo.yml
channels:
- conda-forge
dependencies:
- python=3.8.12
- numpy=1.22.3
```

```yml
# environment-bar.yml
channels:
- conda-forge
dependencies:
- python=3.8.12
- numpy=1.22.2
```

```sh
conda-lock -f environment-foo.yml -f environment-bar.yml -p linux-64
INFO:conda_lock.conda_solver:linux-64 using specs ['python 3.8.12.*', 'numpy 1.22.2.*']
```

```sh
conda-lock -f environment-bar.yml -f environment-foo.yml -p linux-64
INFO:conda_lock.conda_solver:linux-64 using specs ['python 3.8.12.*', 'numpy 1.22.3.*']
```

Is this by design? Would it be possible to resolve to the union of the specified dependencies?
The behavior, if unchanged, should be best documented in [Compound specification](https://github.com/conda-incubator/conda-lock/blob/42923b3bd280a260f1480d45a5c7104546e44580/README.md#compound-specification)

The relevant code seems to be

https://github.com/conda-incubator/conda-lock/blob/42923b3bd280a260f1480d45a5c7104546e44580/conda_lock/src_parser/__init__.py#L336-L346

(As a side note, it looks lines 341-342 are not effective given line 344)
