### ISSUE TITLE
Locking fails when pypi package depends on package being installed via conda

### ISSUE THREAD

**Issue by NatPRoach** [conda-incubator/conda-lock#236]
Hello, I'm attempting to lock the following environment.
```
name: example
channels:
  - conda-forge
  - bioconda
  - default
dependencies:
  - pybedlite=0.0.2
  - pip:
    - fgpyo==0.0.3
```
The dependencies are, simplified, something like this:
```mermaid
graph TD;
    A[.];
    B[fgpyo==0.0.3];
    C[pybedlite=0.0.2];
    D[samwell>=0.0.2];
    E[pybedlite>=0.0.1];
    A-->|pip|B;
    A-->|conda|C;
    B-->D;
    D-->E;
```
`conda-lock` is failing attempting to handle it, seemingly because pybedlite `v0.0.2` isn't on pip due to having a conda-dependency. And apparently `conda-lock` doesn't register that `pybedlite` `>= 0.0.1` is already being installed via conda.

Is there a work-around I'm missing that could possibly fix this?

**Comment by mariusvniekerk** [comment]
No, the pip resolver will probably always fail.  

I would recommend that you get `fgpyo` into conda-forge if possible

**Comment by nh13** [comment]
I am a bit confused, if `conda env install -f env.yml`, it would be unintuitive if `conda-lock` can't lock versions here.  E.g. `conda env export` is able to give package versions.  There's clearly PEBKAC on my end.

**Comment by Kirill888** [comment]
I think I'm having similar problem, but in my case things get solved just fine, but installation fails as windows and macos specific packages get pulled into `linux-64` install via transitive pypi dependencies

```yaml
name: test
channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - python=3.10
  - pip=22.3
  - jupyterlab=3
  - pip:
    - jupyterlab-code-formatter
```

In the above `jupyterlab-code-formatter` depend on `jupyterlab` and nothing else, when installing directly with conda, things are fine. When generating lock file I would expect to only have `jupyterlab-code-formatter` to be installed via `pip`, but I also end up with things like this in the lock file:

```yaml
- dependencies: {}
  hash:
    sha256: 01b6400dd79212f50a2f01af1c65b781290ff39610853db99bf03962eb9a615f
  manager: pip
  name: pywinpty
  platform: linux-64
  source: null
  url: https://files.pythonhosted.org/packages/22/77/59645ee028f410ef1d582fc2923d2cb61016ed38e6ae5022f405227ca2ad/pywinpty-2.0.9.tar.gz
  version: 2.0.9
```

this package is not needed and can not be installed on linux. I believe this is pulled in by `ipython` or `ipykernel`, which are pretty common dependencies to have, and even though these are installed via conda, their pypi dependencies are brought into the environment if any of the `pip` packages have them as direct or transitive dependencies.

I would assume that dependency traversal when looking at pip packages would just stop as soon as conda avaialble dependency is found and be replaced with that conda package, but it looks like tree traversal continues and it also does not take care of platform specific dependencies.

Simply deleting those pypi entries from lock file manually works fine, and then environment can be built and functions fine `pip check` and all that. But deleting things after solving is not great, are there built-in features like "ignore these packages" or similar that I can use to overcome those issues?
