### ISSUE TITLE
Support pre-commit

### ISSUE THREAD

**Issue by maresb** [conda-incubator/conda-lock#237]
It would be nice to make a pre-commit.com-compatible hook so that a Git repository can guarantee that the lockfile is up-to-date.

It would be nice to have a check vs fix feature, depending on whether or not conda-lock should update the working directory.

For speed we should probably default to just checking the hash. But there might be cases where it's desired to relock each time.

**Comment by Riezebos** [comment]
You can already define this hook yourself:
```
  - repo: local
    hooks:
      - id: conda-lock
        name: conda-lock
        entry: conda-lock lock -f environment.yml --check-input-hash
        language: python
        additional_dependencies: ["conda-lock==1.0.5"]
        always_run: true
        pass_filenames: false
```
I use version 1.0.5 because higher versions don't work with CI, as the full path to the environemnt file is stored in the lock file.
