### ISSUE TITLE
Interpreting unsatisfiable specification error messages

### ISSUE THREAD

**Issue by samhedin** [conda-incubator/conda-lock#263]
Hi,
it's not clear to me what the error is here:
```
Could not lock the environment for platform linux-64
The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package pyarrow conflicts for:
rapidsai::cudf -> pyarrow[version='0.12.1.*|0.14.1.*|0.15.0.*|0.17.1.*|>=1.0.1,<1.0.2.0a0|>=4.0.1,<4.0.2.0a0|>=5.0.0,<5.0.1.0a0|>=6.0.1,<6.0.2.0a0|>=7.0.0,<7.0.1.0a0|>=8.0.1,<8.0.2.0a0|>=9.0.0,<9.0.1.0a0',build=*cuda]
nvidia::merlin-core -> pyarrow[version='>=1.0|>=5.0.0']
nvidia::transformers4rec -> pyarrow[version='>=1.0']
nvidia::nvtabular -> pyarrow[version='>=1.0']
```
It seems to me that this should be compatible. `merlin-core, transformers4rec, nvtabular` all require `pyarrow>=1.0`,
and `>=1.0.1` is defined in the `cudf` versions.

Another question:
```
Package merlin-core conflicts for:
nvidia::merlin-core
nvidia|nvidia::merlin-core
nvidia::nvtabular -> merlin-core[version='0.2.0|>=0.2.0']
```
First, why does `merlin-core` depend on `nvidia::merlin-core` and `nvidia|nvidia::merlin-core`?
Second, why is this causing a conflict? The only version constraints are defined in `nvtabular` so it should be good to go? 

Related `environment.yml`:
``` yaml
channels:
  - pytorch
  - conda-forge
  - anaconda
  - rapidsai
  - nvidia
  - nodefaults
dependencies:
  - python=3.9.*
  - pip
  - anaconda::numpy
  - anaconda::mkl
  - nvidia::merlin-core
  - nvidia::transformers4rec
  - nvidia::nvtabular
  - rapidsai::cudf
  - conda-forge::tensorflow
  - conda-forge::tritonclient
  - conda-forge::tritonclient-http
  - conda-forge::tritonclient-grpc

# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-64
```

I'm hardly an expert at Python versioning, I may be missing something obvious here. The above `environment.yml` leads
to more errors when using `conda-lock`, I tried to pick a few representative examples.
