### ISSUE TITLE
Lockfile implementation of categories instead of category

### ISSUE THREAD

**Issue by maresb** [conda-incubator/conda-lock#278]
In order to make it possible to, for instance, reliably install packages in both `dev` and `main`, I proposed in https://github.com/mamba-org/mamba/issues/1209 changing the `category` attribute from a string to a list of strings called `categories`.

There hasn't been any movement yet (which I'm aware of) towards an implementation. I have an idea which might offer an easy way forward, purely in conda-lock at first...

What would happen if we duplicate the entries in the lockfile, so that the lockfile looks roughly like:?

```yaml
- name: common-package
  category: dev
- name: common-package
  category: main
```

If we are lucky, then perhaps the conda-lock and micromamba implementations will follow the expected behavior. (To be tested!) This way we wouldn't need a new lockfile format version.

If this works, this is still rather redundant, but not catastrophically so. We should aim to do better in lockfile format v2. In the meantime, since the micromamba folks believe that extra attributes will be ignored, we could start generating interoperable lockfiles which look like

```yaml
- name: common-package
  category: dev
  categories:
  - main
  - dev
- name: common-package
  category: main
  categories:
  - main
  - dev
```

so that this can be read as v1 by ignoring `categories`, or alternatively read as v2 by ignoring `category` (effectively containing duplicate entries). This way, we could first develop everything in `conda-lock`, and then only once we're ready, work on implementing v2 in micromamba.
