### ISSUE TITLE
Pip dependencies are commented out

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda-incubator/conda-lock#285]
Hello,

When I do:
```bash
conda-lock --file=hcg_hi_analysis.yml --platform=linux-64 --kind=explicit --mamba
```
with the `hcg_hi_analysis.yml` below:
```yaml
name: hcg_hi_analysis
channels:
    - conda-forge
    - astropy
dependencies:
    - python=3.7
    - astropy=4.0
    - numpy=1.16
     # instead of `matplotlib`
    - matplotlib-base=3.1
    - aplpy=2.0
    # instead of `jupyter`
    - jupyterlab
    # for binder
    - jupyterhub-singleuser
    # for oldness
    - jupyter_client=7.1.0
    - jupyter_server=1.13.1
    - astroquery=0.4.1
    - requests=2.22
    - tqdm
    - zenodo_get
    - unzip
    - pip
    - pip:
        - pycf3==2020.12
```
I get pip dependencies commented out in [conda-linux-64.txt](https://github.com/conda-incubator/conda-lock/files/10019113/conda-linux-64.txt).

Specifically:
```
# pip custom-inherit @ https://files.pythonhosted.org/packages/8b/eb/7d530295d32148460e0fc4438b667449082a91badb1f98de4f159dd82a7d/custom_inherit-2.4.0-py3-none-any.whl#sha256=a332144a96ab6a61a81144b23aeac244efb4122a04bb489bbd12bf0624179851
# pip diskcache @ https://files.pythonhosted.org/packages/a1/c4/80d38cf6852ba87f8b506a91f18b3a485c668f452700689add960d7e2ecc/diskcache-5.4.0-py3-none-any.whl#sha256=af3ec6d7f167bbef7b6c33d9ee22f86d3e8f2dd7131eb7c4703d8d91ccdc0cc4
# pip tabulate @ https://files.pythonhosted.org/packages/40/44/4a5f08c96eb108af5cb50b41f76142f0afa346dfa99d5296fe7202a11854/tabulate-0.9.0-py3-none-any.whl#sha256=024ca478df22e9340661486f85298cff5f6dcdba14f3813e8830015b9ed1948f
# pip wrapt @ https://files.pythonhosted.org/packages/49/a8/528295a24655f901148177355edb6a22b84abb2abfadacc1675643c1434a/wrapt-1.14.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=8d649d616e5c6a678b26d15ece345354f7c2286acd6db868e65fcc5ff7c24a77
# pip deprecated @ https://files.pythonhosted.org/packages/51/6a/c3a0408646408f7283b7bc550c30a32cc791181ec4618592eec13e066ce3/Deprecated-1.2.13-py2.py3-none-any.whl#sha256=64756e3e14c8c5eea9795d93c524551432a0be75629f8f29e67ab8caf076c76d
# pip pycf3 @ https://files.pythonhosted.org/packages/99/d2/bf20a8fa9dba1ad18c382f7d6a563ec458ce0b493e480496de31c4e002b7/pycf3-2020.12-py3-none-any.whl#sha256=e874c1b4a682515cc172a5f1599d9cd650b6a719a81261134d05c4fd06864d1d
```
Therefore, the pip dependencies are not available when doing
```bash
mamba create -y --prefix hcg --file conda-linux-64.lock
```

Could you please help?

Many thanks,
Sebastian
