### ISSUE TITLE
Ensure consistent precedence of categories

### ISSUE THREAD

**Issue by g-rutter** [conda-incubator/conda-lock#306]
This is related to #278 and is a much smaller change that could make the current implementation with a single category per package more useful.

# Consistent precedence

Take this command, where the first yml sets `category: dev` and the second `category: main`:

```
conda-lock lock dev-deps.yml main-deps.yml
```

All dependencies which occur in both dep trees should get set to category 'main' - the latter of the ymls specified gets precedence. Then, a working environment will be built whether using `--dev-dependencies` or `--no-dev-dependencies`.

This _almost_ works. The exception is that packages _listed_ in `dev-deps.yml` and _required_ by `main-deps.yml` but not listed explicitly, will get set as `dev'. That means it's excluded from the prod environment even though it's needed!

# Current example

`main-deps.yml`:

```yml
channels:
  - conda-forge

dependencies:
  - python=3.7
  - importlib_metadata
```

`dev-deps.yml`:

```yml
channels:
  - conda-forge

dependencies:
  - python=3.7
  - importlib_metadata
  - importlib-metadata

category: dev
```

Run `conda-lock lock -f dev-deps.yml -f main-deps.yml -p linux-64`

You will see that `importlib-metadata` is considered a 'dev' dependency despite being needed in prod. All other dependencies are correctly labelled 'main'.
