### ISSUE TITLE
Add build string when resolving with --lock-file from environment

### ISSUE THREAD

**Issue by tdejager** [conda-incubator/conda-lock#363]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

It seems that `build` that I assume corresponds to the `build_string` is not filled in when resolving an `environment.yml` file with mamba/micromamba/conda.

```
...snip..
package:
- category: main
  dependencies: {}
  hash:
    md5: d7c89558ba9fa0495403155b64376d81
    sha256: fe51de6107f9edc7aa4f786a70f4a883943bc9d39b3bb7307c04c41410990726
  manager: conda
  name: _libgcc_mutex
  optional: false
  platform: linux-64
  url: https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2
  version: '0.1'
- category: main
  dependencies: {}
  hash:
    md5: ff9f73d45c4a07d6f424495288a26080
    sha256: 8f6c81b0637771ae0ea73dc03a6d30bec3326ba3927f2a7b91931aa2d59b1789
  manager: conda
  name: ca-certificates
  optional: false
  platform: linux-64
  url: https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2022.12.7-ha878542_0.conda
  version: 2022.12.7
- category: main
  dependencies: {}
  hash:
    md5: 7aca3059a1729aa76c597603f10b0dd3
    sha256: f6cc89d887555912d6c61b295d398cff9ec982a3417d38025c45d5dd9b9e79cd
  manager: conda
  name: ld_impl_linux-64
  optional: false
  platform: linux-64
  url: https://conda.anaconda.org/conda-forge/linux-64/ld_impl_linux-64-2.40-h41732ed_0.conda
  version: '2.40'
```
None of the locked packages have the build attribute. Moreover, `conda_solver.py:183` where the structure is being created does not fill it at all. I think the mamba json does return this.

### Why is this needed?

Because it is an identifying feature for a package.

### What should happen?

The code should be modified to fill in the build string where possible. We can now retro-actively extract it from the URL if we want, but I guess this would be more correct.

### Additional Context

We are using the lock-files at [prefix](https://prefix.dev), if you want we could take a stab at a PR :)
