### ISSUE TITLE
Non-optional dependency shows up as optional

### ISSUE THREAD

**Issue by paulius-hydrosat** [conda-incubator/conda-lock#434]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Consider the following pyproject.toml file spec:

```
[tool.poetry.dependencies]
psycopg2 = ">=2.9.1"
python = "==3.11.*"

[tool.poetry.group.prod.dependencies]
dagster_postgres = { version = "==0.19.5", source = "pypi" }
```

After locking, psycopg2 appears as optional dependency:

```
- name: psycopg2
  version: 2.9.3
  manager: conda
  platform: linux-64
  dependencies:
    libgcc-ng: '>=12'
    libpq: '>=15.1,<16.0a0'
    python: '>=3.11,<3.12.0a0'
    python_abi: 3.11.*
  url: https://conda.anaconda.org/conda-forge/linux-64/psycopg2-2.9.3-py311h968e94b_2.conda
  hash:
    md5: fdbb71c126dfaa4149f026c31f536ca8
    sha256: 7bf7e2ba62f0559d92ce1eeff27bf8fecab66803e90ac411255340359642297f
  category: prod
  optional: true
```

It should not, it should be non-optional. I suppose this happens as dagster_postgres is optional and depends on psycopg2.

### Conda Info

```shell
active environment : conda-lock-2
    active env location : /home/psarka/mambaforge/envs/conda-lock-2
            shell level : 3
       user config file : /home/psarka/.condarc
 populated config files : /home/psarka/mambaforge/.condarc
                          /home/psarka/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.4=0
                          __glibc=2.35=0
                          __linux=5.19.0=0
                          __unix=0=0
       base environment : /home/psarka/mambaforge  (writable)
      conda av data dir : /home/psarka/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/psarka/mambaforge/pkgs
                          /home/psarka/.conda/pkgs
       envs directories : /home/psarka/mambaforge/envs
                          /home/psarka/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.28.2 CPython/3.10.10 Linux/5.19.0-43-generic ubuntu/22.04.2 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /home/psarka/mambaforge/.condarc <==
channels:
  - conda-forge

==> /home/psarka/.condarc <==
env_prompt: {default_env}
```

### Additional Context

This is the full pyproject.toml that I'm using:

```
[project]
name = "name"
version = "1.0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.poetry.dependencies]
psycopg2 = ">=2.9.1"
python = "==3.11.*"

[tool.poetry.group.prod.dependencies]
dagster_postgres = { version = "==0.19.5", source = "pypi" }

[tool.conda-lock]
channels = ["conda-forge"]
platforms = ['linux-64']

[tool.conda-lock.dependencies]
pip = ">=23.1"
```
